AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MEWConnect Handshake Server

  SAM Template for the MEWConnect Handshake Server.
  DynamoDB
  S3
  APIGateway

Globals:
  Function:
    Timeout: 30

Parameters:
  TableName:
    Type: String
    Default: 'mewconnect_handshake_connections'
    Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'
  TwilioID:
    Type: String
    Default: 'Please update .env.aws file'
  TwilioToken:
    Type: String
    Default: 'Please update .env.aws file'
  TwilioTTL:
    Type: Number
    Default: 3600

Resources:
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "connectionId"
        AttributeType: "S"
      - AttributeName: "connId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "connectionId"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
      - IndexName: "connIdIndex"
        KeySchema:
        - AttributeName: "connId"
          KeyType: "HASH"
        Projection:
          ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ConnectionsTableStream:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: True
      EventSourceArn:
        Fn::GetAtt: [ ConnectionsTable , StreamArn ]
      FunctionName:
        Fn::GetAtt: [ OnDbEntryFunction, Arn ]
      StartingPosition: LATEST

  OnDbEntryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/lambda/ondbentry/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnectionsTable
      - Statement:
        - Effect: Allow
          Action:
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - dynamodb:Query
          Resource: 
          - "*"
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - 'arn:aws:execute-api:*:*:*/@connections/*'

  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/lambda/onconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnectionsTable
      - Statement:
        - Effect: Allow
          Action:
          - dynamodb:Query
          Resource: 
          - "*"

  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/lambda/ondisconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnectionsTable

  OnTryTurnFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/lambda/ontryturn/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable
          TWILIO_ID: !Ref TwilioID
          TWILIO_TOKEN: !Ref TwilioToken
          TWILIO_TTL: !Ref TwilioTTL
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnectionsTable
      - Statement:
        - Effect: Allow
          Action:
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - dynamodb:Query
          Resource: 
          - "*"
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - 'arn:aws:execute-api:*:*:*/@connections/*'

  OnOfferSignalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/lambda/onoffer/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnectionsTable
      - Statement:
        - Effect: Allow
          Action:
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - dynamodb:Query
          Resource: 
          - "*"
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - 'arn:aws:execute-api:*:*:*/@connections/*'

  OnAnswerSignalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/lambda/onanswer/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnectionsTable
      - Statement:
        - Effect: Allow
          Action:
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - dynamodb:Query
          Resource: 
          - "*"
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - 'arn:aws:execute-api:*:*:*/@connections/*'

  OnRtcConnectedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/lambda/onrtcconnected/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ConnectionsTable
      - Statement:
        - Effect: Allow
          Action:
          - dynamodb:DescribeStream
          - dynamodb:GetRecords
          - dynamodb:GetShardIterator
          - dynamodb:ListStreams
          - dynamodb:Query
          Resource: 
          - "*"
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - 'arn:aws:execute-api:*:*:*/@connections/*'

Outputs:
  ConnectionsTableArn:
    Description: "Connections table ARN"
    Value: !GetAtt ConnectionsTable.Arn

  OnConnectFunctionArn:
    Description: "OnConnect function ARN"
    Value: !GetAtt OnConnectFunction.Arn

  OnDbEntryFunctionArn:
    Description: "OnDbEntry function ARN"
    Value: !GetAtt OnDbEntryFunction.Arn

  OnTryTurnFunctionArn:
    Description: "OnTryTurnfunction ARN"
    Value: !GetAtt OnTryTurnFunction.Arn

  OnOfferSignalFunctionArn:
    Description: "OnOfferSignal function ARN"
    Value: !GetAtt OnOfferSignalFunction.Arn

  OnAnswerSignalFunctionArn:
    Description: "OnAnswerSignal function ARN"
    Value: !GetAtt OnAnswerSignalFunction.Arn

  OnRtcConnectedFunctionArn:
    Description: "OnRtcConnected function ARN"
    Value: !GetAtt OnRtcConnectedFunction.Arn

  OnDisconnectFunctionArn:
    Description: "OnDisconnect function ARN"
    Value: !GetAtt OnDisconnectFunction.Arn