FROM node:12.13.0-alpine

ARG AWSCLI_VERSION
ENV AWSCLI_VERSION=${AWSCLI_VERSION}
ARG AWS_DEFAULT_REGION
ENV AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

RUN apk add --update --no-cache \
    python3-dev \
    gcc \
    libc-dev \
    python3 \
    py3-pip \
    build-base \
    curl \
    unzip \
    bash \
    && pip3 install --upgrade pip \
    && pip3 install awscli --upgrade --user \
    && pip3 install aws-sam-cli==1.12.0 --user \
    && apk --purge -v del py3-pip \
    && rm -rf /var/cache/apk/*


ENV PATH=/root/.local/bin:$PATH

RUN export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
RUN export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
RUN export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

WORKDIR /var/opt
EXPOSE 3000

ENTRYPOINT ["/root/.local/bin/sam"]