FROM node:8.10.0-alpine

ARG AWSCLI_VERSION
ENV AWSCLI_VERSION=${AWSCLI_VERSION}
ARG AWS_DEFAULT_REGION
ENV AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    && pip install --upgrade pip \
    && pip install awscli==$AWSCLI_VERSION --upgrade --user \
    && pip install aws-sam-cli --upgrade --user \
    && apk --purge -v del py-pip \
    && rm -rf /var/cache/apk/*

ENV PATH=/root/.local/bin:$PATH
RUN aws --version

RUN export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
RUN export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
RUN export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

WORKDIR /var/opt

ENTRYPOINT ["/root/.local/bin/sam"]